// <auto-generated />
using System;
using Gestion_Bibliotheque.Infra.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestion_Bibliotheque.Infra.Migrations
{
    [DbContext(typeof(applicationDbContext))]
    partial class applicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("Gestion_Bibliotheque.Domain.Entity.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("b3363f51-d847-45f3-a22f-3a4d70d57d3c"),
                            Name = "Administrateur"
                        },
                        new
                        {
                            RoleId = new Guid("1652b814-0920-47ac-bc63-fd3a6aad4062"),
                            Name = "Etudiant"
                        },
                        new
                        {
                            RoleId = new Guid("3b6cec93-a37b-4e01-b52d-7efa32c298a4"),
                            Name = "Etudiant_VIP"
                        },
                        new
                        {
                            RoleId = new Guid("0fb9e156-a1ee-46f6-88db-bc37c9557d9d"),
                            Name = "Etudiant_Bronze"
                        });
                });

            modelBuilder.Entity("Gestion_Bibliotheque.Domain.Entity.Utilisateur", b =>
                {
                    b.Property<Guid>("UtilisateurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ecol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Isblock")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("JobInTech")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UtilisateurId");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("Gestion_Bibliotheque.Domain.Entity.Utilisateur_Role", b =>
                {
                    b.Property<Guid>("Utilisateur_RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("TEXT");

                    b.HasKey("Utilisateur_RoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Utilisateur_Roles");
                });

            modelBuilder.Entity("RoleUtilisateur", b =>
                {
                    b.Property<Guid>("RolesRoleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("TEXT");

                    b.HasKey("RolesRoleId", "UtilisateurId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("RoleUtilisateur");
                });

            modelBuilder.Entity("Gestion_Bibliotheque.Domain.Entity.Utilisateur_Role", b =>
                {
                    b.HasOne("Gestion_Bibliotheque.Domain.Entity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_Bibliotheque.Domain.Entity.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("RoleUtilisateur", b =>
                {
                    b.HasOne("Gestion_Bibliotheque.Domain.Entity.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_Bibliotheque.Domain.Entity.Utilisateur", null)
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
